apiVersion: "fintlabs.no/v1alpha1"
kind: KafkaUserAndAcl
metadata:
  name: fint-flyt-instance-service
  labels:
    app.kubernetes.io/name: fint-flyt-instance-service
    app.kubernetes.io/instance: fint-flyt-instance-service_vlfk-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: vlfk.no
spec:
  acls:
    - permission: admin
      topic: 'vlfk-no.flyt.*'
---
apiVersion: "fintlabs.no/v1alpha1"
kind: PGSchemaAndUser
metadata:
  name: fint-flyt-instance-service
  labels:
    app.kubernetes.io/name: fint-flyt-instance-service
    app.kubernetes.io/instance: fint-flyt-instance-service_vlfk-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: vlfk.no
spec:
  databaseName: fint_flyt_instance_service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-instance-service
  name: fint-flyt-instance-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-instance-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-instance-service
  labels:
    app: fint-flyt-instance-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vlfk-no-skjema.vigoiks.no`) && PathPrefix(`/api/intern/handlinger/instanser`)
      kind: Rule
      services:
        - name: fint-flyt-instance-service
          port: 8080
      middlewares:
        - name: fint-flyt-auth-forward
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-instance-service
  name: fint-flyt-instance-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-instance-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-instance-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: fint-flyt-instance-service-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-instance-service:dummy
          name: fint-flyt-instance-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: fint-flyt-instance-service-kafka
            - secretRef:
                name: vlfk-no-fint-flyt-instance-service
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: fint.org-id, value: 'vlfk.no' }
            - { name: spring.datasource.hikari.schema, value: 'vlfk_no' }
            - { name: fint.flyt.resource-server.security.api.internal.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.internal.authorized-org-ids, value: 'vlfk.no, vigo.no' }
            - { name: spring.webflux.base-path, value: 'vlfk-no' }