spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${fint.database.username}
    hikari:
      schema: ${fint.database.username}
    url: ${fint.database.url}
    password: ${fint.database.password}

  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300