apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-instance-service_trondelagfylke_no
  fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/trondelagfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/trondelagfylke-no/api/intern/handlinger/instanser"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "trondelagfylke.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: Application
      name: fint-flyt-instance-service


