name: CD

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select and environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
      org:
        description: 'Select organisation'
        required: true
        default: 'warning'
        type: choice
        options:
          - vlfk.no
          - viken.no
          - rogfk.no
          - vtfk.no
          - trondelagfk.no
          - innlandet.no
          - agderfk.no

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_NAME: ${{ inputs.cluster }}

#  ALPHA_CLUSTER_NAME: aks-alpha-fint-2021-11-18
#  ALPHA_CLUSTER_RESOURCE_GROUP: rg-aks-alpha
#  BETA_CLUSTER_NAME: aks-beta-fint-2021-11-23
#  BETA_CLUSTER_RESOURCE_GROUP: rg-aks-beta
#  API_CLUSTER_NAME: aks-api-fint-2022-02-08
#  API_CLUSTER_RESOURCE_GROUP: rg-aks-api

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: rg
        with:
          script: return JSON.stringify(${{ inputs.cluster }})
          result-encoding: string
      - run: |
          echo "Cluster: $CLUSTER_NAME"
          echo "Resource group: $RESOURCE_GROUP"
        env:
          RESOURCE_GROUP: rg-${{ steps.rg }}

#  cd:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v3.1.1
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

      ## Alpha cluster ##
#      - name: Bake alpha manifests with Kustomize
#        uses: azure/k8s-bake@v2.2
#        with:
#          renderEngine: 'kustomize'
#          kustomizationPath: 'kustomize/overlays/alpha'
#        id: bake-alpha
#
#      - name: Set the target Alpha cluster.
#        uses: azure/aks-set-context@v1
#        with:
#          creds: '${{ secrets.AKS_ALPHA_FINT_GITHUB }}'
#          cluster-name: ${{ env.ALPHA_CLUSTER_NAME }}
#          resource-group: ${{ env.ALPHA_CLUSTER_RESOURCE_GROUP }}
#
#      - name: Deploy to Alpha
#        uses: azure/k8s-deploy@v4.4
#        with:
#          manifests: ${{ steps.bake-alpha.outputs.manifestsBundle }}
#          images: |
#            ${{ steps.meta.outputs.tags }}
#          namespace: operators
#          action: deploy